services:
  - type: web
    name: kaumahan-harvest-market
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn kaumahan.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: kaumahan-harvest-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "*"
      - key: MEDIA_URL
        value: "/media/"
      - key: MEDIA_ROOT
        value: "/opt/render/project/src/media"

databases:
  - name: kaumahan-harvest-db
    databaseName: kaumahan_db
    user: kaumahan_user