services:
  - type: web
    name: kaumahan-harvest-market
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn kaumahan.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: kaumahan-harvest-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "*"

databases:
  - name: kaumahan-harvest-db
    databaseName: kaumahan_db
    user: kaumahan_user